// <auto-generated />
using System;
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContextAPI))]
    partial class AppDbContextAPIModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("API.GateTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoopDetector")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReachLowerLimitSwitch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReachUpperLimitSwitch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isSent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("numberOfOpenCurrectly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("numberOfOpenIllegel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GateTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
